server:
  port: 8085

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/academics
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql
      platform: postgres
      continue-on-error: false

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  timelimiter:
    enabled: false

logging:
  level:
    root: error

auth-service:
  url: http://localhost:8084

total-semester-fee: 20000.0
total-reimbursement-fee: 10000.0
