server:
  port: 8080

spring:
  main:
    banner-mode: off

  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
              - "http://localhost:5176"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ==== Academic Related ====
        - id: academics-service
          uri: lb://ACADEMICS-SERVICE
          predicates:
            - Path=/academics/**, /api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: academicsServiceCircuit
                fallbackUri: forward:/fallback/academics

        # ==== Admin Related ====
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminServiceCircuit
                fallbackUri: forward:/fallback/admin

        # ==== Auth ====
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**, /api/authz/**
          filters:
            - PreserveHostHeader
            - name: CircuitBreaker
              args:
                name: authServiceCircuit
                fallbackUri: forward:/fallback/auth

        # ==== Catalog & Library ====
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/catalog/**
          filters:
            - name: CircuitBreaker
              args:
                name: libraryServiceCircuit
                fallbackUri: forward:/fallback/library

        - id: categories-service
          uri: lb://CATEGORIES-SERVICE
          predicates:
            - Path=/api/v1/categories/**

        # ==== Dashboard ====
        - id: dashboard-service
          uri: lb://DASHBOARD-SERVICE
          predicates:
            - Path=/api/v1/dashboards/**

        # ==== Issue Handling ====
        - id: issue-service
          uri: lb://ISSUE-SERVICE
          predicates:
            - Path=/api/issues/**

        # ==== Notifications ====
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**

        # ==== Review ====
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**

        # ==== Search ====
        - id: search-service
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/api/search/**

        # ==== Student ====
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuit
                fallbackUri: forward:/fallback/student

        # ==== OAuth Endpoint (Internal) ====
        - id: library-oauth
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/oauth/lib

        # ==== Attendance ====
        - id: attendance-service
          uri: lb://ATTENDANCE-SERVICE
          predicates:
            - Path=/api/attendance/**

        # ==== BFF (Backend For Frontend) ====
        - id: bff-service
          uri: lb://BFF-SERVICE
          predicates:
            - Path=/api/bff/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    root: error
    org.springframework.cloud.gateway: debug
    org.springframework.web.reactive: debug
    reactor.netty.http.server: debug
