server:
  port: 8080

spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuit
                fallbackUri: forward:/fallback/student

        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/**
          filters:
            - name: CircuitBreaker
              args:
                name: libraryServiceCircuit
                fallbackUri: forward:/fallback/library

        - id: library-service-oauth
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/oauth/lib

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminServiceCircuit
                fallbackUri: forward:/fallback/admin

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuit
                fallbackUri: forward:/fallback/auth
                
        - id: academics-service
          uri: lb://ACADEMICS-SERVICE
          predicates:
            - Path=/academics/**, /api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: academicsServiceCircuit
                fallbackUri: forward:/fallback/academics


        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
          # filters:
          #   - name: CircuitBreaker
          #     args:
          #       name: notificationServiceCircuit
          #       fallbackUri: forward:/fallback/notification

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5

logging:
  level:
    root: error
