server:
  port: 8080

spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/**
            - Path=/oauth/lib
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/oauth/lib
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
        - id: academics-service
          uri: lb://ACADEMICS-SERVICE
          predicates:
            - Path=/academics/**

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5

logging:
  level:
    root: error
    # org.springframework: WARN
    # org.hibernate.SQL: DEBUG
    # org.cms: DEBUG
    # org.apache: WARN
