server:
  port: 8080

spring:
  main:
    banner-mode: off

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
              - "http://localhost:5176"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - name: CircuitBreaker
              args:
                name: studentServiceCircuit
                fallbackUri: forward:/fallback/student

        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/library/**
          filters:
            - name: CircuitBreaker
              args:
                name: libraryServiceCircuit
                fallbackUri: forward:/fallback/library

        - id: library-service-oauth
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/oauth/lib

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminServiceCircuit
                fallbackUri: forward:/fallback/admin

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuit
                fallbackUri: forward:/fallback/auth
            # Uncomment this if your controller paths do not include `/api/auth`
            # - RewritePath=/api/auth/(?<segment>.*), /${segment}

        - id: academics-service
          uri: lb://ACADEMICS-SERVICE
          predicates:
            - Path=/academics/**, /api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: academicsServiceCircuit
                fallbackUri: forward:/fallback/academics

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5

logging:
  level:
    root: error
    org.springframework.cloud.gateway: debug
    org.springframework.web.reactive: debug
    reactor.netty.http.server: debug
