server:
  port: 8084
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
