server:
  port: 9999

spring:
  application:
    name: bff-service

  main:
    banner-mode: "off"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
