server:
  port: 8082

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: info

library:
  book:
    noOfReturnDays: 10
