server:
  port: 8091

spring:
  main:
    banner-mode: off

  application:
    name: categories-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/category_db
    username: postgres
    password: root

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql
      platform: postgres
      continue-on-error: true

  data:
    r2dbc:
      repositories:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: error
