spring:
  application:
    name: department-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/department_db?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update      
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      platform: mysql
      mode: always

server:
  port: 8089

eureka:
  register-with-eureka: true
  fetch-registry: true
  server:
    defaultZone: http://localhost:8761/eureka/

spring:
  profiles:
    active: dev
