server:
  port: 8761
spring:
  main:
    banner-mode: off
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    root: error
    # INFO  # Sets the default logging level to INFO
  #   org.springframework: WARN  # Reduces Spring framework logs to avoid clutter
  #   org.hibernate.SQL: DEBUG  # Logs SQL queries for debugging
  #   org.cms: DEBUG  # Enables detailed logging for your application packages
  #   org.apache: WARN  # Suppresses excessive logging from Apache libraries

  # pattern:
  #   console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # Improved log format
  #   file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  

  # file:
  #   name: logs/application.log  # Saves logs to a file
  #   max-size: 10MB  # Limits log file size
  #   max-history: 10  # Keeps the last 10 log files

