server:
  port: 8088

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/library_issue_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
