server:
  port: 8082

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO 

library:
  book:
    noOfReturnDays: 10


