server:
  port: 8089

spring:
  application:
    name: review-service

  main:
    banner-mode: "off"

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library_reviews_db
    username: postgres
    password: root

  # This section is only for schema.sql initialization (via JDBC fallback)
  datasource:
    url: jdbc:postgresql://localhost:5432/library_reviews_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: postgres
      continue-on-error: true

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
