server:
  port: 8089

spring:
  application:
    name: review-service

  main:
    banner-mode: "off"

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library_reviews_db
    username: postgres
    password: root

  # JDBC-based init is not used for R2DBC, included here just for clarity
  sql:
    init:
      mode: always
      platform: postgres

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
