server:
  port: 8089

spring:
  main:
    banner-mode: "off"

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library_reviews_db
    username: postgres
    password: root

  sql:
    init:
      mode: always
      platform: postgres

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
