server:
  port: 8089

spring:
  main:
    banner-mode: off

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library_reviews_db

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
