spring:
  application:
    name: search-service
    
elasticsearch:
  host: localhost
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8087
