server:
  port: 8087  # ✅ Choose a unique port if running standalone (optional if behind Eureka)

elasticsearch:
  host: localhost
  port: 9200
  
spring:
  application:
    name: search-service

  main:
    banner-mode: off

  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

logging:
  level:
    root: error
    org.springframework.web.reactive.function.client: debug
    org.springframework.cloud.gateway: DEBUG
    

