spring:
  application:
    name: survey-forms

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: survey-forms-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091
