spring:
  application:
    name: survey-forms

  datasource:
    url: jdbc:postgresql://localhost:5432/survey_forms
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # options: validate | update | create | create-drop | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: false
      encoding: UTF-8

  cloud:
    config:
      enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: survey-forms-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091
